# Generated by Django 5.1.3 on 2024-11-22 07:29

import apps.blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('KP', '科普'), ('SW', '散文'), ('XS', '小说'), ('YX', '游戏')], db_comment='Category name', max_length=50)),
                ('category_type', models.CharField(choices=apps.blog.models.Category.get_currencies, default='KP', max_length=50)),
                ('category_text', models.CharField(choices=[('KP', '科普'), ('SW', '散文'), ('XS', '小说'), ('YX', '游戏')], max_length=50, verbose_name='Category text')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('pub_time', models.TimeField(auto_now_add=True)),
                ('status', models.BooleanField(db_comment='Published or not', default=False)),
                ('user', models.CharField(max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
