# Generated by Django 5.1.3 on 2024-11-27 03:53

import apps.blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_book_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('DE', 'German'), ('EN', 'English'), ('CN', 'Chinese'), ('ES', 'Spanish')], default=apps.blog.models.Choices.LanguageChoice['CN'], max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('category_type', models.CharField(choices=[('KP', '科普'), ('SW', '散文'), ('XS', '小说'), ('YX', '游戏')], default='KP', max_length=2)),
                ('level', models.CharField(choices=[('FR', '大一新生'), ('SO', '大二'), ('JR', '初级'), ('SR', '高级'), ('GR', '毕业生')], db_comment='level', help_text='Level with no default value', max_length=2)),
                ('region', models.CharField(choices=[('华北', 'Hb'), ('华南', 'Hn'), ('华东', 'Hd'), ('华中', 'Hz')], default='华北', help_text='Region with no default value', max_length=2)),
                ('answer', models.CharField(choices=[(None, '(Unknown)'), (0, 'No'), (1, 'Yes')], max_length=2, verbose_name='answer')),
                ('suit', models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], default=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='category',
        ),
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='价格'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
