# Generated by Django 5.1.3 on 2024-11-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_choices_remove_author_category_author_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='medal_type',
            field=models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], default='BRONZE', max_length=10, verbose_name='MedalType'),
        ),
        migrations.AddField(
            model_name='choices',
            name='place',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], default=3, verbose_name='Place'),
        ),
    ]
