# Generated by Django 5.1.3 on 2024-11-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_choices_medal_type_choices_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=5),
        ),
    ]
