# Generated by Django 5.1.3 on 2024-11-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_choices_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='answer',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (0, 'No'), (1, 'Yes')], verbose_name='answer'),
        ),
    ]
