# Generated by Django 5.1.3 on 2024-11-27 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_author_books_book_author_alter_choices_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='tags',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='the related book'),
        ),
    ]
