# Generated by Django 5.1.3 on 2024-11-28 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_man_woman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='woman',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='woman',
            name='woman_list',
        ),
        migrations.CreateModel(
            name='MobileProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.project')),
                ('device', models.CharField(max_length=20)),
                ('developers', models.ManyToManyField(related_name='mobile_projects', to='blog.person')),
            ],
            bases=('blog.project',),
        ),
        migrations.CreateModel(
            name='WebProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.project')),
                ('url', models.URLField()),
                ('administrators', models.ManyToManyField(related_name='web_projects', to='blog.person')),
            ],
            bases=('blog.project',),
        ),
        migrations.DeleteModel(
            name='Man',
        ),
        migrations.DeleteModel(
            name='Woman',
        ),
    ]
