# Generated by Django 5.1.3 on 2024-11-28 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_project_remove_woman_person_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavaWebProject',
            fields=[
                ('webproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.webproject')),
                ('framework', models.CharField(max_length=20)),
            ],
            bases=('blog.webproject',),
        ),
    ]
