# Generated by Django 5.1.3 on 2024-12-06 04:17

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_publisher_books_club_employee_reader_club_reader'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('entries', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='choices',
            name='fruit',
            field=models.IntegerField(choices=[(1, '苹果'), (2, '桃子'), (3, '橘子')], default=1),
        ),
        migrations.AlterField(
            model_name='choices',
            name='category_type',
            field=models.CharField(choices=[('K', '科普'), ('S', '散文'), ('X', '小说'), ('Y', '游戏')], default='K', max_length=2),
        ),
    ]
