# Generated by Django 5.1.3 on 2024-12-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_pizza_topping_restaurant_pizza_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
