# Generated by Django 5.1.3 on 2024-12-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='json',
            field=models.JSONField(default=dict, null=True, verbose_name='JSON数据'),
        ),
    ]
